### ISSUE TITLE
Move to pcdshub

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lcls-plc-txi-optics#1]
@jsheppard95 can you move this plc project to pcdshub?

**Comment by jsheppard95** [comment]
Just transferred the ownership. I haven't used that tool before so let me know if anything looks off.

**Comment by ZLLentz** [comment]
Thanks Jackson, looks good to me!
Didn't even notice this wasn't on pcdshub until the SLAC site power outage forced me to poke all the motion-related PLCs
